server:
  port: 8080

spring:
  application:
    name: etl-api

kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  config:
    topic: ${CONFIG_TOPIC:etl.config.v1}

logging:
  level:
    com.etl.api: DEBUG
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"