spring:
  application:
    name: etl-file-producer

kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  input:
    topic: ${INPUT_TOPIC:etl.input.v1}

producer:
  rate:
    per:
      sec: ${RATE_PER_SEC:10}

logging:
  level:
    com.etl.producer: INFO
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"